export * from './address-endpoint.service';
import { AddressEndpointService } from './address-endpoint.service';
export * from './address-endpoint.serviceInterface';
export * from './artist-endpoint.service';
import { ArtistEndpointService } from './artist-endpoint.service';
export * from './artist-endpoint.serviceInterface';
export * from './custom-health-endpoint.service';
import { CustomHealthEndpointService } from './custom-health-endpoint.service';
export * from './custom-health-endpoint.serviceInterface';
export * from './event-endpoint.service';
import { EventEndpointService } from './event-endpoint.service';
export * from './event-endpoint.serviceInterface';
export * from './hall-plan-endpoint.service';
import { HallPlanEndpointService } from './hall-plan-endpoint.service';
export * from './hall-plan-endpoint.serviceInterface';
export * from './location-endpoint.service';
import { LocationEndpointService } from './location-endpoint.service';
export * from './location-endpoint.serviceInterface';
export * from './login-endpoint.service';
import { LoginEndpointService } from './login-endpoint.service';
export * from './login-endpoint.serviceInterface';
export * from './message-endpoint.service';
import { MessageEndpointService } from './message-endpoint.service';
export * from './message-endpoint.serviceInterface';
export * from './news-endpoint.service';
import { NewsEndpointService } from './news-endpoint.service';
export * from './news-endpoint.serviceInterface';
export * from './order-endpoint.service';
import { OrderEndpointService } from './order-endpoint.service';
export * from './order-endpoint.serviceInterface';
export * from './show-endpoint.service';
import { ShowEndpointService } from './show-endpoint.service';
export * from './show-endpoint.serviceInterface';
export * from './ticket-endpoint.service';
import { TicketEndpointService } from './ticket-endpoint.service';
export * from './ticket-endpoint.serviceInterface';
export * from './user-endpoint.service';
import { UserEndpointService } from './user-endpoint.service';
export * from './user-endpoint.serviceInterface';
export const APIS = [AddressEndpointService, ArtistEndpointService, CustomHealthEndpointService, EventEndpointService, HallPlanEndpointService, LocationEndpointService, LoginEndpointService, MessageEndpointService, NewsEndpointService, OrderEndpointService, ShowEndpointService, TicketEndpointService, UserEndpointService];
