/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ArtistDto } from '../model/models';
import { PageArtistSearchResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ArtistEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param artistId 
     */
    findById4(artistId: number, extraHttpRequestParams?: any): Observable<ArtistDto>;

    /**
     * 
     * 
     * @param firstname 
     * @param lastname 
     * @param artistName 
     * @param page 
     * @param size 
     * @param sort 
     */
    search1(firstname?: string, lastname?: string, artistName?: string, page?: number, size?: number, sort?: string, extraHttpRequestParams?: any): Observable<PageArtistSearchResponse>;

}
