/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EventCreationDto } from '../model/models';
import { EventDto } from '../model/models';
import { EventResponse } from '../model/models';
import { EventWithTicketCountDto } from '../model/models';
import { PageEventResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param eventCreationDto 
     */
    createEvent(eventCreationDto: EventCreationDto, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     * @param artistId 
     */
    findByArtist(artistId: number, extraHttpRequestParams?: any): Observable<Array<EventResponse>>;

    /**
     * 
     * 
     * @param eventid 
     */
    findById3(eventid: number, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     */
    getTop10EventsWithMostTickets(extraHttpRequestParams?: any): Observable<Array<EventWithTicketCountDto>>;

    /**
     * 
     * 
     * @param textSearch 
     * @param typ 
     * @param dauer 
     * @param page 
     * @param size 
     * @param sort 
     */
    searchEvents(textSearch?: string, typ?: 'CONCERT' | 'THEATER' | 'PLAY', dauer?: number, page?: number, size?: number, sort?: string, extraHttpRequestParams?: any): Observable<PageEventResponse>;

}
