/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EventCreationDto } from '../model/models';
import { EventDto } from '../model/models';
import { EventResponse } from '../model/models';
import { EventSearchDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param eventCreationDto 
     */
    createEvent(eventCreationDto: EventCreationDto, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     * @param artistId 
     */
    findByArtist(artistId: number, extraHttpRequestParams?: any): Observable<Array<EventResponse>>;

    /**
     * 
     * 
     * @param eventid 
     */
    findById3(eventid: number, extraHttpRequestParams?: any): Observable<EventDto>;

    /**
     * 
     * 
     * @param eventSearchDto 
     */
    searchEvents(eventSearchDto: EventSearchDto, extraHttpRequestParams?: any): Observable<Array<EventDto>>;

}
