/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HallPlanDto } from '../model/models';
import { HallplanCreateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HallPlanEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param name 
     */
    findByName(name: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param body 
     */
    getById(body: number, extraHttpRequestParams?: any): Observable<HallPlanDto>;

    /**
     * 
     * 
     * @param hallplanCreateRequest 
     */
    register1(hallplanCreateRequest: HallplanCreateRequest, extraHttpRequestParams?: any): Observable<object>;

}
