/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DetailedMessageDto } from '../model/models';
import { MessageInquiryDto } from '../model/models';
import { SimpleMessageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MessageEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Publish a new message
     * 
     * @param messageInquiryDto 
     */
    create(messageInquiryDto: MessageInquiryDto, extraHttpRequestParams?: any): Observable<DetailedMessageDto>;

    /**
     * Get detailed information about a specific message
     * 
     * @param id 
     */
    find(id: number, extraHttpRequestParams?: any): Observable<DetailedMessageDto>;

    /**
     * Get list of messages without details
     * 
     */
    findAll(extraHttpRequestParams?: any): Observable<Array<SimpleMessageDto>>;

}
