/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TicketDetailsResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TicketEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    findById(id: number, extraHttpRequestParams?: any): Observable<TicketDetailsResponse>;

    /**
     * 
     * 
     */
    findForUser(extraHttpRequestParams?: any): Observable<Array<TicketDetailsResponse>>;

}
