/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationUserDto } from '../model/models';
import { ApplicationUserResponse } from '../model/models';
import { UserCreateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserEndpointServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getUser(extraHttpRequestParams?: any): Observable<ApplicationUserResponse>;

    /**
     * 
     * 
     * @param userCreateRequest 
     */
    register(userCreateRequest: UserCreateRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param firstName 
     * @param familyName 
     * @param email 
     * @param isLocked 
     */
    searchUsers(firstName?: string, familyName?: string, email?: string, isLocked?: boolean, extraHttpRequestParams?: any): Observable<Array<ApplicationUserDto>>;

    /**
     * 
     * 
     * @param applicationUserDto 
     */
    updateUserStatusByEmail(applicationUserDto: ApplicationUserDto, extraHttpRequestParams?: any): Observable<ApplicationUserResponse>;

}
