/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventSearchDto { 
    dauer?: number;
    typ?: EventSearchDto.TypEnum;
    textSearch?: string;
}
export namespace EventSearchDto {
    export type TypEnum = 'CONCERT' | 'THEATER' | 'PLAY';
    export const TypEnum = {
        Concert: 'CONCERT' as TypEnum,
        Theater: 'THEATER' as TypEnum,
        Play: 'PLAY' as TypEnum
    };
}


