/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShowResponse } from './show-response';
import { HallSectorResponse } from './hall-sector-response';


export interface HallSectorShowResponse { 
    id?: number;
    show?: ShowResponse;
    sector?: HallSectorResponse;
    price?: number;
}

