/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HallPlan } from './hall-plan';
import { HallSpot } from './hall-spot';


export interface HallSector { 
    id?: number;
    hallPlan?: HallPlan;
    name?: string;
    frontendCoordinates?: string;
    seats?: Array<HallSpot>;
}

