/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HallplanSectionCreateRequest } from './hallplan-section-create-request';


export interface HallplanCreateRequest { 
    name: string;
    backgroundImage: string;
    sectors: Array<HallplanSectionCreateRequest>;
    id?: number;
}

