/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HallPlanDto } from './hall-plan-dto';
import { AddressDto } from './address-dto';


export interface LocationDto { 
    id?: number;
    name?: string;
    address?: AddressDto;
    hallPlan?: HallPlanDto;
}

