/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetailsResponse } from './order-details-response';
import { ShowResponse } from './show-response';
import { TicketDetailsResponseHallSpot } from './ticket-details-response-hall-spot';


export interface TicketDetailsResponse { 
    id?: number;
    hash?: string;
    reserved?: boolean;
    valid?: boolean;
    hallSpot?: TicketDetailsResponseHallSpot;
    show?: ShowResponse;
    order?: OrderDetailsResponse;
}

