/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShowResponse } from './show-response';
import { HallSpotResponse } from './hall-spot-response';


export interface TicketDetailsResponse { 
    id?: number;
    hash?: string;
    reserved?: boolean;
    valid?: boolean;
    hallSpot?: HallSpotResponse;
    show?: ShowResponse;
}

